# Generated by Django 4.0.3 on 2022-03-15 02:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prix', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('reduction', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('like', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TypeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image_article')),
                ('couleur', models.CharField(max_length=15)),
                ('tailles_disponibles', models.CharField(max_length=10)),
                ('quantite_diponible', models.PositiveSmallIntegerField()),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.article')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(blank=True, null=True)),
                ('article', models.ManyToManyField(blank=True, to='gestion.article')),
            ],
        ),
        migrations.CreateModel(
            name='Cathegorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image_cathegorie')),
                ('nom', models.CharField(max_length=15)),
                ('cathegorie_superieure', models.ManyToManyField(to='gestion.cathegorie')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='cathegorie',
            field=models.ManyToManyField(to='gestion.cathegorie'),
        ),
    ]
