# Generated by Django 4.0.3 on 2022-03-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathegorie',
            name='cathegorie_superieure',
            field=models.ManyToManyField(blank=True, to='gestion.cathegorie'),
        ),
    ]
