# Generated by Django 4.0.3 on 2022-03-24 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0013_alter_cathegorie_accompagnement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='article',
            new_name='articles',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='date_commande',
        ),
        migrations.AddField(
            model_name='panier',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
