# Generated by Django 4.0.3 on 2022-04-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_panier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='articles',
        ),
        migrations.AddField(
            model_name='panier',
            name='type_articles',
            field=models.ManyToManyField(blank=True, to='gestion.typearticle'),
        ),
    ]
