# Generated by Django 4.0.3 on 2022-03-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_cathegorie_cathegorie_superieure'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTypeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='image_type_article')),
                ('photo2', models.ImageField(upload_to='image_type_article')),
                ('photo3', models.ImageField(upload_to='image_type_article')),
            ],
        ),
        migrations.RemoveField(
            model_name='typearticle',
            name='photo',
        ),
        migrations.AddField(
            model_name='typearticle',
            name='photos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.phototypearticle'),
        ),
    ]
