# Generated by Django 4.0.3 on 2022-03-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_article_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typearticle',
            name='photos',
        ),
        migrations.AddField(
            model_name='typearticle',
            name='photo1',
            field=models.ImageField(default='fdsf', upload_to='image_type_article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typearticle',
            name='photo2',
            field=models.ImageField(default='flsdjflkds', upload_to='image_type_article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typearticle',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='image_type_article'),
        ),
        migrations.DeleteModel(
            name='PhotoTypeArticle',
        ),
    ]
