# Generated by Django 4.0.3 on 2022-03-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_typearticle_photos_typearticle_photo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosTypeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='image_type_article')),
                ('photo2', models.ImageField(upload_to='image_type_article')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='image_type_article')),
            ],
        ),
        migrations.RenameField(
            model_name='typearticle',
            old_name='quantite_diponible',
            new_name='quantite_disponible',
        ),
        migrations.RenameField(
            model_name='typearticle',
            old_name='tailles_disponibles',
            new_name='taille',
        ),
        migrations.RemoveField(
            model_name='typearticle',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='typearticle',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='typearticle',
            name='photo3',
        ),
        migrations.AddField(
            model_name='typearticle',
            name='photos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.photostypearticle'),
        ),
    ]
