# Generated by Django 4.0.3 on 2022-03-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_photostypearticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photostypearticle',
            name='nom',
            field=models.CharField(default='tml', max_length=30),
            preserve_default=False,
        ),
    ]
