# Generated by Django 4.0.3 on 2022-03-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_photostypearticle_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='/'),
        ),
        migrations.AddField(
            model_name='article',
            name='origine',
            field=models.CharField(default='/s', max_length=15),
        ),
        migrations.AlterField(
            model_name='cathegorie',
            name='cathegorie_superieure',
            field=models.ManyToManyField(blank=True, related_name='sous_cathegories', to='gestion.cathegorie'),
        ),
    ]
