# Generated by Django 4.0.3 on 2022-03-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_cathegorie_accompagement_delete_accompagnement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cathegorie',
            old_name='accompagement',
            new_name='accompagnement',
        ),
    ]
