# Generated by Django 4.0.4 on 2022-05-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0005_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
    ]
