# Generated by Django 4.0.4 on 2022-05-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresse',
            old_name='Quartier',
            new_name='quartier',
        ),
    ]
