# Generated by Django 4.0.4 on 2022-05-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_rename_quartier_adresse_quartier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name': 'pays', 'verbose_name_plural': 'pays'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'default_permissions': 'add'},
        ),
    ]
