# Generated by Django 4.0.4 on 2022-05-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'default_permissions': 'view'},
        ),
    ]
